"""Orchestrates the quantitative and qualitative evaluation of alert analyses.

This script acts as the primary execution entry point to process candidate model
inferences and compare them with ground truth references, and selectively invoke
BLEURT scoring or evaluation based on criteria set by LLM.
"""

import argparse
import time
from datetime import datetime
from pathlib import Path
from src.config import main_config as conf
from src.evaluation.evaluator import Evaluator
from src.utils import data_handler


def main(
    analysis_filepath: Path,
    ground_truths_filepath: Path,
    judge_prompt_filepath: Path,
    first_id: int,
    last_id: int,
    rep_num: int,
    skip_bleurt: bool,
    skip_llm_judge: bool
):
    """Orchestrates the evaluation of a model's analysis against a ground truth 
    reference.

    Configures the underlying Evaluator class with appropriate filtering 
    windows, performs BLEURT scoring and LLM judge procedures conditionally 
    based on runtime flags, translates metrics into proper output shape 
    formats, and writes the results to the disk with unique filesystem tokens.

    Args:
        analysis_filepath: Path to the candidate model inference JSON logfile.
        ground_truths_filepath: Path to the master reference Excel file.
        judge_prompt_filepath: Path to the text file with judge prompts.
        first_id: First alert ID to analyze.
        last_id: Last alert ID to analyze.
        rep_num: Number of analysis repetitions for statistical assessment.
        skip_bleurt: Flag to indicate if BLEURT scoring needs to be skipped.
        skip_llm_judge: Flag to indicate if LLM judge procedure needs to be skipped.
    """
    print(
        "-"*50 + f"\n--- Starting evaluation for: {analysis_filepath.name} ---")

    # Load and parse the necessary data
    evaluator = Evaluator(
        analysis_filepath=analysis_filepath,
        ground_truth_filepath=ground_truths_filepath,
        judge_prompt_filepath=judge_prompt_filepath,
        first_alert_id=first_id,
        last_alert_id=last_id
    )

    # Run different evaluation methods
    if not skip_bleurt:
        bleurt_scores = evaluator.calculate_bleurt_scores()
    else:
        bleurt_scores = "Skipped"
    if not skip_llm_judge:
        judge_results = evaluator.run_llm_as_judge(rep_num)
    else:
        judge_results = "Skipped"

    # Note evaluation results and info
    timestamp_out = time.strftime("%Y-%m-%dT%H:%M:%SZ")
    time.strftime("%Y_%m_%d-%H_%M_%S")
    evaluation_output = {
        "source_analysis_file": analysis_filepath.name,
        "ground_truth_file": ground_truths_filepath.name,
        "evaluation_timestamp": timestamp_out,
        "bleurt_scores": bleurt_scores,
        "llm_judge_scores": judge_results
    }

    # Save evaluation results; filename is derived from the input analysis file
    timestamp_filename = datetime.strptime(
        timestamp_out, "%Y-%m-%dT%H:%M:%SZ").strftime("%Y_%m_%d-%H_%M_%S")
    output_filename = f"eval_{analysis_filepath.stem}_{timestamp_filename}.json"
    output_path = Path("results/evaluation") / output_filename

    data_handler.save_json(evaluation_output, output_path)
    print(f" - Evaluation results saved successfully to: {output_path}")
    print("--- Evaluation completed ---\n" + "-"*50)


if __name__ == "__main__":
    # Run 'python -m src.run_evaluations "<analysis_filepath>"'
    # or  'python -m src.run_evaluations "<analysis_filepath>" --first_id=<int> --last_id=<int> --rep_num=<int>'
    project_dir = Path(conf.PROJECT_DIR)
    ground_truths_path = project_dir / "data" / conf.TEST_ALERTS_FILE
    parser = argparse.ArgumentParser(
        description="Run evaluation on a generated alert analysis file."
    )

    parser.add_argument(
        "analysis_filepath",
        type=str,
        help="Path to the analysis JSON file generated by main.py."
    )
    parser.add_argument(
        "--skip_bleurt",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Skips BLEURT score calculation if flag is set."
    )
    parser.add_argument(
        "--skip_llm_judge",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Skips LLM-as-a-judge evaluation if flag is set."
    )
    parser.add_argument(
        "--ground_truths_filepath",
        type=str,
        default=ground_truths_path,
        help="Path to the corresponding ground truth Excel file."
    )
    parser.add_argument(
        "--judge_prompt",
        type=str,
        default="prompts/llm_judge_prompt.txt",
        help="Alert ID "
    )
    parser.add_argument(
        "--first_id",
        type=int,
        default=conf.FIRST_ALERT_ID,
        help="Start evaluation at this alert ID."
    )
    parser.add_argument(
        "--last_id",
        type=int,
        default=conf.LAST_ALERT_ID,
        help="End evaluation at this alert ID."
    )
    parser.add_argument(
        "--rep_num",
        type=int,
        default=None,
        help="Only this repetition will be evaluated by the llm judge (BLEURT unaffected)."
    )

    args = parser.parse_args()

    main(
        analysis_filepath=Path(args.analysis_filepath),
        ground_truths_filepath=Path(args.ground_truths_filepath),
        judge_prompt_filepath=Path(args.judge_prompt),
        first_id=args.first_id,
        last_id=args.last_id,
        rep_num=args.rep_num,
        skip_bleurt=args.skip_bleurt,
        skip_llm_judge=args.skip_llm_judge
    )
